site_name: Brainary
site_description: Brainary documentation
site_author: NTU SPRL

docs_dir: docs

theme:
  name: material

nav:
  - Home: QUICKSTART.md
  - Guide:
      - User Manual: USER_MANUAL.md
      - API: API_REFERENCE.md


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - footnotes
  - md_in_html


plugins:
  - search


plugins:
  - search
  - autorepo
